### PR TITLE
Deglob doctests and use set and map literals

### PR DESCRIPTION
**Pull request by lnicola**

### CODE REVIEW

**Comment by notriddle** [comment]
Can we unhide the `extern crate maplit` line? We need to mention where the `hashset!` and `hashmap!` macros are coming from, otherwise users who're copy-pasting the examples will end up very confused.

**Comment by lnicola** [comment]
Done. I wonder whether we should also unhide the `extern crate ammonia;` declarations.

**Comment by notriddle** [comment]
Why? You're already reading the `ammonia` docs.

bors r+

**Comment by lnicola** [comment]
> Why? You're already reading the ammonia docs.

Guess so :smile:. In the past I've had trouble with crates where the crate and repository names were different, but that's not the case here.

**Pull request merged**
