### PR TITLE
Allow writing the output to a stream

### LINKED ISSUE #42: Allow more general output types
Just like we did in #38, we might want to avoid a buffering step for the output. API proposal:

```rust
struct AmmoniaDocument(RcDom);

impl AmmoniaDocument {
    pub fn to_string(&self) -> String;
    pub fn write_to<W: Write>(&self, writer: &mut W);
    pub fn into_rcdom(self) -> RcDom; // or Handle? might be useful, but do we really want to?
}
```

Part of #31.

### PR DESCRIPTION
**Pull request by lnicola**
Closes #42

### CODE REVIEW

**Comment by notriddle** [comment]
🚲 🏠 

* Rename `Ammonia` to `Builder`
* Rename `AmmoniaDoc` to `Document`

**Comment by lnicola** [comment]
I still need to write some documentation and update the CI files.

**Comment by lnicola** [comment]
And the README..

**Comment by lnicola** [comment]
The README looks fine, actually.

**Pull request merged**
