### PR TITLE
Allow passing in the HTML with a reader

### LINKED ISSUE #38: Allow more general input types
We might want to make `clean` work with something that's more general than `&str`, like `Read`.

See https://doc.servo.org/tendril/stream/trait.TendrilSink.html.

### PR DESCRIPTION
**Pull request by lnicola**
Errors are not handling yet. We can change those when we decide what to
do for the rest of the code.

Fixes #38

Do we also want to do something like this for the output?

### CODE REVIEW

**Comment by lnicola** [comment]
There's also a `from_iter` variant that would work with iterators returning slices (I assume), but I'm not sure we want to have that.

**Comment by notriddle** [comment]
Some reason `clean_from_reader` can't just return `Result<String, io::Error>`, and have the function be this?

```rust

    pub fn clean_from_reader<R>(&self, src: &mut R) -> std::io::Result<String>
    where
        R: std::io::Read,
    {
        let parser = Self::make_parser().from_utf8();
        let dom = parser.read_from(src)?;
        Ok(self.clean_dom(dom))
    }
```

**Comment by lnicola** [comment]
It could, but if we switch to `error-chain` or custom errors, the result type will probably change.

**Comment by notriddle** [comment]
bors r+

It's not like we haven't been pretty liberal with breaking changes here, already. It probably would be a good idea to start using a private field on the Ammonia struct, so we can start having non-breaking feature changes (and mark it as 1.0).

**Comment by lnicola** [comment]
Maybe after we finish with #31?

**Pull request merged**
