### PR TITLE
Add categories to Cargo.toml

### PR DESCRIPTION
**Pull request by notriddle**
Part of #31

### CODE REVIEW

**Comment by lnicola** [comment]
I'm not convinced that `text-processing` is intended for this, but other crates (like `regex`) use it, so I guess it's fine.

**Comment by lnicola** [comment]
r+

**Comment by notriddle** [comment]
I just added you as a reviewer, @lnicola, so do it again and it'll work.

**Comment by lnicola** [comment]
Thanks!

bors r+

**Pull request merged**
