### PR TITLE
Link to the CHANGELOG (C-RELNOTES)

### PR DESCRIPTION
**Pull request by lnicola**
Also add an "Unreleased" changelog entry.

Part of #31

### CODE REVIEW

**Comment by notriddle** [comment]
[0.7.0 is released](https://crates.io/crates/ammonia)

**Comment by lnicola** [comment]
The plan was to add new stuff under `Unreleased`, then move it below on releases. Not sure how to make this clearer (maybe leave an empty bullet?).

**Comment by notriddle** [comment]
The empty bullet seems fine.

**Comment by lnicola** [comment]
Done.

**Pull request merged**
